export const BUY_PRODUCT = "BUY_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCT = "DELETE_ALL_PRODUCT";
export const LOAD_DATA_LS = "LOAD_DATA_LS";
export const QUANTITY_MINUS = "QUANTITY_MINUS";